baseurl: 

title: Stepping Stone Nutrition, LLC
author: Stepping Stone Nutrition, LLC
email: your-email@domain.com
description: Stepping Stone Nutrition offers Nutrition, Wellness, and Lactation Counseling and Services in Southeast Wisconsin.
url: www.steppingstonenutritionwi.com
logo: /images/logo.svg

repository: chrisgozd/steppingstonesnutrition.github.io

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# Build settings
markdown: kramdown
theme: minima

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag
  - jekyll-minifier

exclude:
  - Gemfile
  - Gemfile.lock
  - /docs